fix: try again

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -44,14 +44,32 @@ workflows:
     - script@1:
         title: Get latest XCode version
         inputs:
-        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug
-            log\nset +x\necho \"=======================\"\necho \"READING ENV VAR\"\necho
-            \"=======================\"\necho \necho \"CONTENTS of SEMVER_PREV ENV
-            VAR....\"\necho\necho $SEMVER_PREV\n\n\ncurl https://bootstrap.pypa.io/3.2/get-pip.py
-            -o python3.2\npip3 install -r ./requirements.txt\npython3 ./run.py\n\n\necho
-            \"=======================\"\necho \"SEMVER_PREV WRITTEN BY: run.py\"\necho
-            \"=======================\"\necho \necho \"CONTENTS of SEMVER_PREV FILE....\"\necho\ncat
-            ./SEMVER_PREV\necho \necho \"A.B.C\" > SEMVER_PREV\n\n\n\n\n"
+        - content: 
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            debug log
+            set +x
+            echo "======================="
+            echo "READING ENV VAR"
+            echo "======================="
+            echo 
+            echo "CONTENTS of SEMVER_PREV ENV VAR...."
+            echo 
+            echo $SEMVER_PREV
+            curl https://bootstrap.pypa.io/3.2/get-pip.py -o python3.2
+            pip3 install -r ./requirements.txt
+            pip3 freeze
+            python3 ./run.py
+            echo "======================="
+            echo "SEMVER_PREV WRITTEN BY: run.py"
+            echo "======================="
+            echo 
+            echo "CONTENTS of SEMVER_PREV FILE...."
+            echo
+            cat ./SEMVER_PREV
+            echo 
+            echo "A.B.C" > SEMVER_PREV
         is_always_run: true
     - script@1:
         inputs:
